version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: serviceup
      POSTGRES_USER: serviceup_user
      POSTGRES_PASSWORD: serviceup_password
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: